spring.application.name=msa
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=mt1398bd
spring.neo4j.authentication.database=neo4j




